# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db639c7aa9ae730cfc4380ce7c90a90fe5f006a7563bf3bea2bc9eabe65cdfdb3e3965272e8b892fc8c6cb77a6d68aab1f4f829cdf3162da06fcc118b8d58fe9

test:
  secret_key_base: 41f37d2b46f47bcc727927a193536be180f286f75abdb5ca8bcae5fdb8c988150748b78930dadecf5a14aba65c1e45663fbb68487d062fa29c2f2779b93fec14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
